apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: restricted-role-operator

configurations:
- base/kustomizeconfig/openshift-config.yaml

resources:
- base/buildconfig.yaml
- base/deploymentconfig.yaml
- base/imagestream.yaml
- base/serviceaccount.yaml
