apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: restricted-role-operator
  name: restricted-role-operator
spec:
  failedBuildsHistoryLimit: 5
  output:
    to:
      kind: ImageStreamTag
      name: restricted-role-operator:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      uri: https://github.com/buehlmann/restricted-role-operator
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: restricted-role-operator-base:latest
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
  - type: ConfigChange
  - imageChange:
      lastTriggeredImageID: 
    type: ImageChange
