apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: restricted-role-operator
  name: restricted-role-operator
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    app: restricted-role-operator
    deploymentconfig: restricted-role-operator
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        app: restricted-role-operator
        deploymentconfig: restricted-role-operator
    spec:
      containers:
      - env:
          - name: NAMESPACE_FILTER
            value: <replace-me>
        name: restricted-role-operator
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          protocol: TCP 
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 45Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: restricted-role-operator
      serviceAccountName: restricted-role-operator
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - type: ConfigChange
  - type: ImageChange
    imageChangeParams:
      automatic: true
      containerNames:
      - restricted-role-operator
      from:
        kind: ImageStreamTag
        name: restricted-role-operator:latest
